<?php
echo "<!doctype html>\n"; 
echo "<html lang=\"en\">\n"; 
echo "\n"; 
echo "<head>\n"; 
echo "  <title>Title</title>\n"; 
echo "  <!-- Required meta tags -->\n"; 
echo "  <meta charset=\"utf-8\">\n"; 
echo "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n"; 
echo "\n"; 
echo "  <!-- Bootstrap CSS -->\n"; 
echo "  <link href=\"https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\" rel=\"stylesheet\" integrity=\"sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN\" crossorigin=\"anonymous\">\n"; 
echo "  <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\"\n"; 
echo "    integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">\n"; 
echo "  <link rel=\"stylesheet\" href=\"styles/main.css\">\n"; 
echo "</head>\n"; 
echo "\n"; 
echo "<body>\n"; 
echo "  <div class=\"container-fluid\">\n"; 
echo "    <div id=\"navBar\" class=\"row d-flux justify-content-between\">\n"; 
echo "      <div id=\"img\"class=\"col\">\n"; 
echo "        <img src=\"assets/yardLogo.png\">\n"; 
echo "      </div>\n"; 
echo "      <div id=\"nav\" class=\"col d-flex justify-content-end\">\n"; 
echo "        <ul class=\"\">\n"; 
echo "          <li>\n"; 
echo "            <a href=\"#\">O NAMA</a>\n"; 
echo "          </li>\n"; 
echo "          <li>\n"; 
echo "            <a href=\"#\">KONTAKT</a>\n"; 
echo "          </li>\n"; 
echo "          <li>\n"; 
echo "            <a href=\"#\">PRIJAVI SE</a>\n"; 
echo "          </li>\n"; 
echo "        </ul>\n"; 
echo "      </div>\n"; 
echo "    </div>\n"; 
echo "    <div id=\"mobileDisplay\" class=\"row\">\n"; 
echo "\n"; 
echo "    </div>\n"; 
echo "    <div class=\"row\">\n"; 
echo "      <div id=\"introText\" class=\"col\">\n"; 
echo "        <p>Yard obuke je platforma za stručno i profesionalno usavršavanje <br>su oblasti Marketinga, Informacionih Tehnologija i Komunikacija</p>\n"; 
echo "      </div>\n"; 
echo "      <div class=\"col hide\">\n"; 
echo "\n"; 
echo "      </div>\n"; 
echo "    </div>\n"; 
echo "    <div class=\"row\">\n"; 
echo "      <div id=\"jumboTron\" class=\"col\">\n"; 
echo "        <p>OD KURSEVA DO SERTIFIKACIJE</p>\n"; 
echo "      </div>\n"; 
echo "      <div class=\"col hide\">\n"; 
echo "\n"; 
echo "      </div>\n"; 
echo "    </div>\n"; 
echo "    <div class=\"row\">\n"; 
echo "      <div id=\"prestiz\" class=\"col\">\n"; 
echo "        <p>100% obuka prema programu predavača sa prestižnim iskustvima globalnog poslovanja i edukacija</p>\n"; 
echo "      </div>\n"; 
echo "      <div class=\"col hide\">\n"; 
echo "\n"; 
echo "      </div>\n"; 
echo "    </div>\n"; 
echo "    <div class=\"row\">\n"; 
echo "      <div id=\"userExperiance\" class=\"col\">\n"; 
echo "        <p>Budite u koraku sa novim konceptom i pristupom usvajanja i primene znanja sa vodećim ekspertima IT tehnologija, user experience marketinga i komunikacija koji će učiniti da steknete znanja i veštine i iskustvo koji su vam <br>potrebni.\n"; 
echo "          <br>\n"; 
echo "          Skupovima delatnosti koje se bave marketingom i Customer Care... su potrebne najnovije veštine da bi efikasno obavljali svoj posao. A liderima različitih industrija je potrebna vidljivost kako njihovi timovi rade na tome da prave ljuide prave pravim projektima. Pluralnost vam daje i oboje - veštine i podatke koji su vam potrebni za uspeh\n"; 
echo "        </p>\n"; 
echo "      </div>\n"; 
echo "      <div class=\"col hide\">\n"; 
echo "\n"; 
echo "      </div>\n"; 
echo "    </div>\n"; 
echo "    <div class=\"row\">\n"; 
echo "      <div id=\"prednostiPristupa\" class=\"col\">\n"; 
echo "        <p>PREDNOSTI NAŠEG PRISTUPA</p>\n"; 
echo "        <br>\n"; 
echo "      \n"; 
echo "      </div>\n"; 
echo "      <div class=\"col hide\">\n"; 
echo "\n"; 
echo "      </div>\n"; 
echo "    </div>\n"; 
echo "    <div class=\"row\">\n"; 
echo "      <div id=\"ikoniceTekst\" class=\"col\">\n"; 
echo "        <img src=\"assets/icons.png\">\n"; 
echo "        <br>\n"; 
echo "       \n"; 
echo "      </div>\n"; 
echo "      <div class=\"col hide\">\n"; 
echo "\n"; 
echo "      </div>\n"; 
echo "    </div>\n"; 
echo "    <div id=\"footer\" class=\"row d-flex justify-content-between\">\n"; 
echo "      \n"; 
echo "        <div class=\"col\">\n"; 
echo "          <ul>\n"; 
echo "            <li>\n"; 
echo "              <a href=\"mailto:office@yard.rs\">office@yard.rs</a>\n"; 
echo "            </li>\n"; 
echo "            <li>\n"; 
echo "              <a href=\"https://www.google.com/maps/place/Gospodar+Jovanova+3,+Beograd\">Gospodar Jovanova 3, Beograd</a>\n"; 
echo "            </li>\n"; 
echo "            <li>\n"; 
echo "              <a href=\"tel:+381621889930\">+381 62 188 99 30</a>\n"; 
echo "            </li>\n"; 
echo "          </ul>\n"; 
echo "        </div>\n"; 
echo "        <div id=\"dugmad\" class=\"col d-flex justify-content-end\">\n"; 
echo "          <button id=\"dugme\">PRIJAVA</button>\n"; 
echo "        </div>\n"; 
echo "      \n"; 
echo "    </div>\n"; 
echo "    <div id=\"mobileDugme\">\n"; 
echo "      \n"; 
echo "      <button id=\"mobileBtn\">\n"; 
echo "        PRIJAVI SE\n"; 
echo "      </button>\n"; 
echo "    </div>\n"; 
echo "  </div>\n"; 
echo "\n"; 
echo "  <script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\"\n"; 
echo "    integrity=\"sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo\"\n"; 
echo "    crossorigin=\"anonymous\"></script>\n"; 
echo "  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\"\n"; 
echo "    integrity=\"sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1\"\n"; 
echo "    crossorigin=\"anonymous\"></script>\n"; 
echo "  <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\"\n"; 
echo "    integrity=\"sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM\"\n"; 
echo "    crossorigin=\"anonymous\"></script>\n"; 
echo "</body>\n"; 
echo "\n"; 
echo "</html>\n";
?>